// swift-tools-version:5.9
import PackageDescription

// Local Swift package wrapping the `crates/ffi` UniFFI bridge (Phase 4 D2).
//
// Layout:
//   Frameworks/ffiFFI.xcframework      — GITIGNORED. Regenerate with
//                                        apps/ios/build-ffi.sh (device + sim
//                                        static-lib slices built from crates/ffi
//                                        --features goose,whisper). Each slice is
//                                        libffi.a merged with the whisper/ggml
//                                        static archives (libwhisper.a, libggml*.a).
//   Sources/AthanorCoreFFI/ffi.swift   — generated by uniffi-bindgen; COMMITTED
//                                        (matches the checked-in Rust surface;
//                                        regenerated by the same script whenever
//                                        the FFI surface changes).
//
// `ffiFFI` (binaryTarget) is the raw C symbols + module map from the Rust
// staticlib (the module name is fixed by uniffi's crate-name "ffi" → "ffiFFI",
// which the generated ffi.swift imports). `AthanorCoreFFI` is the Swift-facing
// target the app imports.
//
// linkerSettings: whisper-rs-sys's cmake asks cargo to link these frameworks +
// libc++ (spike-whisper-report §3). cargo records the request in libffi's
// metadata but a static-lib link doesn't propagate it, so the app target must
// carry them here. Metal/MetalKit/Accelerate power the ggml backend; libc++ is
// whisper.cpp's C++ runtime.
let package = Package(
    name: "AthanorCoreFFI",
    platforms: [.iOS(.v17)],
    products: [
        .library(name: "AthanorCoreFFI", targets: ["AthanorCoreFFI"]),
    ],
    targets: [
        .binaryTarget(
            name: "ffiFFI",
            path: "Frameworks/ffiFFI.xcframework"
        ),
        .target(
            name: "AthanorCoreFFI",
            dependencies: ["ffiFFI"],
            path: "Sources/AthanorCoreFFI",
            linkerSettings: [
                .linkedLibrary("c++"),
                .linkedFramework("Accelerate"),
                .linkedFramework("Foundation"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
            ]
        ),
    ]
)
