#!/usr/bin/env bash
# Generates Athanor.xcodeproj. Two modes, chosen automatically by whether the
# (gitignored) AthanorCoreFFI xcframework exists:
#
#   xcframework present  -> REAL athanor-core engine. Reads ANTHROPIC_API_KEY,
#                           writes the gitignored project.local.yml (build
#                           setting), and generates from project-real.yml
#                           (demo base + project.local.yml + the AthanorCoreFFI
#                           package dependency).
#   xcframework absent   -> DEMO engine. Generates from project.yml alone, and
#                           tells you to run ./build-ffi.sh to upgrade.
#
# A clean checkout with no setup still builds: bare `xcodegen generate` (or this
# script's demo branch) produces the DemoEngine app with zero dependencies.
#
# --- Secret flow (no secret ever touches a tracked file) ---
#   repo-root .env  ANTHROPIC_API_KEY  ->  gitignored apps/ios/project.local.yml
#   (build setting ANTHROPIC_API_KEY)  ->  xcodebuild expands $(ANTHROPIC_API_KEY)
#   into the built app's Info.plist at build time; RealEngineLoader reads it once
#   at first launch and copies it into the iOS Keychain, then constructs the FFI
#   AthanorEngine from the Keychain copy.
#
# TRUTH (plan review #5): the build-setting path embeds the key in the BUILT
# APP's Info.plist. That is fine for a single-device dogfood build — the Keychain
# copy adds no bundle secrecy. Do NOT ship this to a multi-tester TestFlight: it
# would distribute the key. A key-free bundle needs a runtime paste-field flow,
# which is not built (not needed day-1).
#
# The key VALUE is never printed, echoed, or read into a shell variable that gets
# logged — it is piped blind from .env straight into the 0600 project.local.yml.
#
# Usage: cd apps/ios && ./generate.sh
set -euo pipefail
cd "$(dirname "$0")"                 # apps/ios
REPO_ROOT="$(cd ../.. && pwd)"
ENV_FILE="$REPO_ROOT/.env"
LOCAL="project.local.yml"
XCFRAMEWORK="Packages/AthanorCoreFFI/Frameworks/ffiFFI.xcframework"

if [ ! -d "$XCFRAMEWORK" ]; then
  echo "NOTE: $XCFRAMEWORK not found — generating the DEMO project." >&2
  echo "      Run ./build-ffi.sh, then ./generate.sh again, for the real core." >&2
  xcodegen generate
  echo "==> generated Athanor.xcodeproj (DEMO engine)"
  exit 0
fi

# Resolve the key: explicit env wins, else read from .env. Never printed.
KEY=""
if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  KEY="$ANTHROPIC_API_KEY"
elif [ -f "$ENV_FILE" ] && grep -qE '^ANTHROPIC_API_KEY=' "$ENV_FILE"; then
  KEY="$(grep -E '^ANTHROPIC_API_KEY=' "$ENV_FILE" | head -1 | cut -d= -f2-)"
fi

if [ -z "$KEY" ]; then
  echo "WARN: no ANTHROPIC_API_KEY in env or $ENV_FILE." >&2
  echo "      The real core is linked but the app falls back to the DEMO engine" >&2
  echo "      at runtime until a key is present." >&2
fi

# Dev seed fixtures (optional): gitignored sqlite dbs built with `athanor-cli
# seed` (see docs/research/lived-seed-mapping.md). When present, their absolute
# paths are baked into the build so a DEBUG install seeds itself on first launch
# (RealEngineLoader, #if DEBUG) — no `seed-db=` arg to remember. Paths are NOT
# secrets; the seeded data never enters git (fixtures live under gitignored
# /seeds/). Release builds ignore all of this.
#
# Two fixtures: the operator's PRIVATE lived seed (from ~/athanor) and the
# committed "normy" demo persona (`athanor-cli seed --profile normy`). The
# DEFAULT the app seeds is the lived one if present, else normy; `seed-profile=
# normy` at launch always selects normy.
LIVED_SEED="$REPO_ROOT/seeds/lived.seed.sqlite"
NORMY_SEED="$REPO_ROOT/seeds/normy.seed.sqlite"
SEED_FIXTURE=""
if [ -f "$LIVED_SEED" ]; then
  SEED_FIXTURE="$LIVED_SEED"
  echo "NOTE: found lived-in dev seed — DEBUG installs seed from it by default." >&2
elif [ -f "$NORMY_SEED" ]; then
  SEED_FIXTURE="$NORMY_SEED"
  echo "NOTE: found normy demo seed — DEBUG installs seed from it by default." >&2
fi
NORMY_FIXTURE=""
if [ -f "$NORMY_SEED" ]; then NORMY_FIXTURE="$NORMY_SEED"; fi

# Write the gitignored local spec (0600). The key VALUE is never echoed (it
# stays inside the heredoc, redirected straight to the 0600 file).
umask 077
cat > "$LOCAL" <<EOF
# AUTO-GENERATED by ./generate.sh from .env — gitignored, never commit.
settings:
  base:
    ANTHROPIC_API_KEY: "$KEY"
EOF
if [ -n "$SEED_FIXTURE" ]; then
  # Paths only — not secrets. Appended (not in the heredoc) for clarity.
  echo "    ATHANOR_DEV_SEED_DB: \"$SEED_FIXTURE\"" >> "$LOCAL"
fi
if [ -n "$NORMY_FIXTURE" ]; then
  echo "    ATHANOR_DEV_SEED_DB_NORMY: \"$NORMY_FIXTURE\"" >> "$LOCAL"
fi

xcodegen generate --spec project-real.yml
echo "==> generated Athanor.xcodeproj (REAL athanor-core engine active when a key was found)"
