#!/usr/bin/env bash
# Generates Athanor.xcodeproj. Two modes, chosen automatically by whether the
# (gitignored) AthanorCoreFFI xcframework exists:
#
#   xcframework present  -> REAL athanor-core engine. Reads ANTHROPIC_API_KEY,
#                           writes the gitignored project.local.yml (build
#                           setting), and generates from project-real.yml
#                           (demo base + project.local.yml + the AthanorCoreFFI
#                           package dependency).
#   xcframework absent   -> DEMO engine. Generates from project.yml alone, and
#                           tells you to run ./build-ffi.sh to upgrade.
#
# A clean checkout with no setup still builds: bare `xcodegen generate` (or this
# script's demo branch) produces the DemoEngine app with zero dependencies.
#
# --- Secret flow (no secret ever touches a tracked file) ---
#   repo-root .env  ANTHROPIC_API_KEY  ->  gitignored apps/ios/project.local.yml
#   (build setting ANTHROPIC_API_KEY)  ->  xcodebuild expands $(ANTHROPIC_API_KEY)
#   into the built app's Info.plist at build time; RealEngineLoader reads it once
#   at first launch and copies it into the iOS Keychain, then constructs the FFI
#   AthanorEngine from the Keychain copy.
#
# TRUTH (plan review #5): the build-setting path embeds the key in the BUILT
# APP's Info.plist. That is fine for a single-device dogfood build — the Keychain
# copy adds no bundle secrecy. Do NOT ship this to a multi-tester TestFlight: it
# would distribute the key. A key-free bundle needs a runtime paste-field flow,
# which is not built (not needed day-1).
#
# The key VALUE is never printed, echoed, or read into a shell variable that gets
# logged — it is piped blind from .env straight into the 0600 project.local.yml.
#
# Usage: cd apps/ios && ./generate.sh
set -euo pipefail
cd "$(dirname "$0")"                 # apps/ios
REPO_ROOT="$(cd ../.. && pwd)"
ENV_FILE="$REPO_ROOT/.env"
LOCAL="project.local.yml"
XCFRAMEWORK="Packages/AthanorCoreFFI/Frameworks/ffiFFI.xcframework"

if [ ! -d "$XCFRAMEWORK" ]; then
  echo "NOTE: $XCFRAMEWORK not found — generating the DEMO project." >&2
  echo "      Run ./build-ffi.sh, then ./generate.sh again, for the real core." >&2
  xcodegen generate
  echo "==> generated Athanor.xcodeproj (DEMO engine)"
  exit 0
fi

# Resolve the key: explicit env wins, else read from .env. Never printed.
KEY=""
if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  KEY="$ANTHROPIC_API_KEY"
elif [ -f "$ENV_FILE" ] && grep -qE '^ANTHROPIC_API_KEY=' "$ENV_FILE"; then
  KEY="$(grep -E '^ANTHROPIC_API_KEY=' "$ENV_FILE" | head -1 | cut -d= -f2-)"
fi

if [ -z "$KEY" ]; then
  echo "WARN: no ANTHROPIC_API_KEY in env or $ENV_FILE." >&2
  echo "      The real core is linked but the app falls back to the DEMO engine" >&2
  echo "      at runtime until a key is present." >&2
fi

# Dev lived-in seed fixture (optional): a gitignored sqlite the operator built
# with `athanor-cli seed` (see docs/research/lived-seed-mapping.md). When present,
# its absolute path is baked into the build so a DEBUG install seeds itself on
# first launch (RealEngineLoader, #if DEBUG) — no `seed-db=` arg to remember.
# The path is NOT a secret; the seeded data never enters git (the fixture lives
# under gitignored /seeds/). Release builds ignore it.
SEED_FIXTURE=""
SEED_CANDIDATE="$REPO_ROOT/seeds/lived.seed.sqlite"
if [ -f "$SEED_CANDIDATE" ]; then
  SEED_FIXTURE="$SEED_CANDIDATE"
  echo "NOTE: found lived-in dev seed fixture — DEBUG installs will seed on first launch." >&2
fi

# Write the gitignored local spec (0600). The key VALUE is never echoed (it
# stays inside the heredoc, redirected straight to the 0600 file).
umask 077
cat > "$LOCAL" <<EOF
# AUTO-GENERATED by ./generate.sh from .env — gitignored, never commit.
settings:
  base:
    ANTHROPIC_API_KEY: "$KEY"
EOF
if [ -n "$SEED_FIXTURE" ]; then
  # Path only — not a secret. Appended (not in the heredoc) for clarity.
  echo "    ATHANOR_DEV_SEED_DB: \"$SEED_FIXTURE\"" >> "$LOCAL"
fi

xcodegen generate --spec project-real.yml
echo "==> generated Athanor.xcodeproj (REAL athanor-core engine active when a key was found)"
